from __future__ import annotations

# Blog
TITLE_MIN_LENGTH = 1
TITLE_MAX_LENGTH = 255
TEXT_MIN_LENGTH = 1
IMAGE_KEY_MAX_LENGTH = 1024
PAGE_DEFAULT = 1
PAGE_SIZE_DEFAULT = 20
PAGE_SIZE_MIN = 1
PAGE_SIZE_MAX = 50
SEARCH_MIN_LENGTH = 1

# Auth
EMAIL_MIN_LENGTH = 3
EMAIL_MAX_LENGTH = 50
PHONE_MAX_LENGTH = 32
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128

# JWT
JWT_DEFAULT_SECRET = "dev-insecure-secret"
JWT_DEFAULT_ALGORITHM = "HS256"
JWT_DEFAULT_ACCESS_TTL_MINUTES = 60
JWT_DEFAULT_EMAIL_CONFIRM_TTL_MINUTES = 24 * 60
JWT_MAX_ACCESS_TTL_MINUTES = 24 * 60
JWT_CLAIM_SUB = "sub"
JWT_CLAIM_EMAIL = "email"
JWT_CLAIM_EXP = "exp"
JWT_CLAIM_TOKEN_TYPE = "token_type"
JWT_TOKEN_TYPE_EMAIL_CONFIRM = "email_confirm"

# Печеньки
AUTH_COOKIE_NAME_DEFAULT = "access_token"
AUTH_COOKIE_SAMESITE_DEFAULT = "lax"
AUTH_COOKIE_HTTPONLY = True

# API роуты и МВ
API_V1_PREFIX = "/api/v1"
AUTH_PREFIX = "/auth"
AUTH_TAG = "auth"
AUTH_REGISTER_PATH = f"{API_V1_PREFIX}{AUTH_PREFIX}/register"
AUTH_LOGIN_PATH = f"{API_V1_PREFIX}{AUTH_PREFIX}/login"
AUTH_CONFIRM_EMAIL_ENDPOINT = "/confirm-email"
AUTH_CONFIRM_EMAIL_PATH = f"{API_V1_PREFIX}{AUTH_PREFIX}{AUTH_CONFIRM_EMAIL_ENDPOINT}"
OPENAPI_PATH = "/openapi.json"
DOCS_PATH_PREFIX = "/docs"
REDOC_PATH_PREFIX = "/redoc"
HTTP_OPTIONS_METHOD = "OPTIONS"

# Auth сообщения
AUTH_DETAIL_NOT_AUTHENTICATED = "Not authenticated"
AUTH_DETAIL_INVALID_OR_EXPIRED_TOKEN = "Invalid or expired token"
AUTH_DETAIL_INVALID_CREDENTIALS = "Invalid email or password"
AUTH_DETAIL_LOGIN_SUCCESS = "Login successful"
AUTH_DETAIL_USER_EMAIL_EXISTS = "User with this email already exists"
AUTH_DETAIL_USER_EMAIL_OR_PHONE_EXISTS = "User with this email or phone already exists"
AUTH_DETAIL_EMAIL_CONFIRMED = "Email confirmed successfully"
AUTH_DETAIL_EMAIL_ALREADY_CONFIRMED = "Email is already confirmed"
AUTH_DETAIL_INVALID_OR_EXPIRED_CONFIRM_TOKEN = (
    "Invalid or expired email confirmation token"
)

# ДБ ошибка
DATABASE_URL_IS_NOT_SET_ERROR = "DATABASE_URL is not set"
