from __future__ import annotations

TITLE_MIN_LENGTH = 1
TITLE_MAX_LENGTH = 255
TEXT_MIN_LENGTH = 1
IMAGE_KEY_MAX_LENGTH = 1024

PAGE_DEFAULT = 1
PAGE_SIZE_DEFAULT = 20
PAGE_SIZE_MIN = 1
PAGE_SIZE_MAX = 50
SEARCH_MIN_LENGTH = 1
