from __future__ import annotations

from app.constants_api import API_V1_PREFIX

# Auth
EMAIL_MIN_LENGTH = 3
EMAIL_MAX_LENGTH = 50
PHONE_MAX_LENGTH = 32
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128

# JWT
JWT_DEFAULT_SECRET = "dev-insecure-secret"
JWT_DEFAULT_ALGORITHM = "HS256"
JWT_DEFAULT_ACCESS_TTL_MINUTES = 60
JWT_DEFAULT_EMAIL_CONFIRM_TTL_MINUTES = 24 * 60
JWT_DEFAULT_REFRESH_TTL_MINUTES = 7 * 24 * 60
JWT_MAX_ACCESS_TTL_MINUTES = 24 * 60
JWT_CLAIM_SUB = "sub"
JWT_CLAIM_EMAIL = "email"
JWT_CLAIM_EXP = "exp"
JWT_CLAIM_IAT = "iat"
JWT_CLAIM_JTI = "jti"
JWT_CLAIM_TOKEN_TYPE = "token_type"
JWT_TOKEN_TYPE_ACCESS = "access"
JWT_TOKEN_TYPE_EMAIL_CONFIRM = "email_confirm"
JWT_TOKEN_TYPE_REFRESH = "refresh"
JWT_REFRESH_TOKEN_ID_LENGTH = 32

# Refresh token store
AUTH_REFRESH_STORE_BACKEND_DB = "db"
AUTH_REFRESH_STORE_BACKEND_MEMORY = "memory"
AUTH_REFRESH_STORE_BACKEND_REDIS = "redis"
AUTH_REFRESH_STORE_BACKEND_DEFAULT = AUTH_REFRESH_STORE_BACKEND_DB
AUTH_REDIS_URL_DEFAULT = "redis://localhost:6379/0"
AUTH_REFRESH_REDIS_KEY_PREFIX_DEFAULT = "auth:refresh:token"

# Cookies
AUTH_COOKIE_NAME_DEFAULT = "access_token"
AUTH_REFRESH_COOKIE_NAME_DEFAULT = "refresh_token"
AUTH_COOKIE_SAMESITE_DEFAULT = "lax"
AUTH_COOKIE_HTTPONLY = True
AUTH_COOKIE_DOMAIN_DEFAULT = ""

# API routes
AUTH_PREFIX = "/auth"
AUTH_TAG = "auth"
AUTH_REGISTER_PATH = f"{API_V1_PREFIX}{AUTH_PREFIX}/register"
AUTH_LOGIN_PATH = f"{API_V1_PREFIX}{AUTH_PREFIX}/login"
AUTH_CONFIRM_EMAIL_ENDPOINT = "/confirm-email"
AUTH_CONFIRM_EMAIL_PATH = f"{API_V1_PREFIX}{AUTH_PREFIX}{AUTH_CONFIRM_EMAIL_ENDPOINT}"
AUTH_REFRESH_ENDPOINT = "/refresh"
AUTH_REFRESH_PATH = f"{API_V1_PREFIX}{AUTH_PREFIX}{AUTH_REFRESH_ENDPOINT}"
AUTH_LOGOUT_ENDPOINT = "/logout"
AUTH_LOGOUT_PATH = f"{API_V1_PREFIX}{AUTH_PREFIX}{AUTH_LOGOUT_ENDPOINT}"
AUTH_COOKIE_PATH_ACCESS = API_V1_PREFIX
AUTH_COOKIE_PATH_REFRESH = f"{API_V1_PREFIX}{AUTH_PREFIX}"

# Auth messages
AUTH_DETAIL_NOT_AUTHENTICATED = "Not authenticated"
AUTH_DETAIL_INVALID_OR_EXPIRED_TOKEN = "Invalid or expired token"
AUTH_DETAIL_INVALID_CREDENTIALS = "Invalid email or password"
AUTH_DETAIL_AUTH_SERVICE_UNAVAILABLE = "Authentication service unavailable"
AUTH_DETAIL_LOGIN_SUCCESS = "Login successful"
AUTH_DETAIL_EMAIL_NOT_CONFIRMED = "Email is not confirmed"
AUTH_DETAIL_REFRESH_SUCCESS = "Token refreshed successfully"
AUTH_DETAIL_LOGOUT_SUCCESS = "Logged out successfully"
AUTH_DETAIL_USER_EMAIL_EXISTS = "User with this email already exists"
AUTH_DETAIL_USER_EMAIL_OR_PHONE_EXISTS = "User with this email or phone already exists"
AUTH_DETAIL_EMAIL_CONFIRMED = "Email confirmed successfully"
AUTH_DETAIL_EMAIL_ALREADY_CONFIRMED = "Email is already confirmed"
AUTH_DETAIL_INVALID_OR_EXPIRED_CONFIRM_TOKEN = (
    "Invalid or expired email confirmation token"
)
AUTH_DETAIL_INVALID_OR_EXPIRED_REFRESH_TOKEN = "Invalid or expired refresh token"
